import Link from 'next/link'
import { Video } from 'lucide-react'

export default function TermsPage() {
  const EFFECTIVE_DATE = 'June 25, 2026'
  const CONTACT_EMAIL = 'onlinemoneyrcc@gmail.com'

  return (
    <div className="min-h-screen bg-[#0f0f0f] text-[#fafafa]">
      <header className="border-b border-[#2a2a2a] px-6 py-4">
        <Link href="/dashboard" className="flex items-center gap-2 w-fit">
          <div className="w-8 h-8 bg-violet-600 rounded-lg flex items-center justify-center">
            <Video className="w-4 h-4 text-white" />
          </div>
          <span className="text-sm font-bold text-white">UGC Pro Studio</span>
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-white mb-2">Terms &amp; Conditions</h1>
        <p className="text-[#a3a3a3] text-sm mb-10">Effective date: {EFFECTIVE_DATE}</p>

        <div className="space-y-8 text-[#c3c3c3] text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance</h2>
            <p>By accessing or using UGC Pro Studio (&ldquo;the Service&rdquo;) you agree to these Terms. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Eligibility</h2>
            <p>You must be at least 18 years old to use the Service. By using it you represent and warrant that you meet this requirement.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. Your API Key &amp; Costs</h2>
            <p>The Service uses your Google Gemini API key to generate scripts and videos. You are solely responsible for:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>All API costs billed by Google to your account.</li>
              <li>Keeping your API key confidential and setting appropriate spending limits in Google AI Studio.</li>
              <li>Revoking and replacing your key if you suspect it has been compromised.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>Generate content that is illegal, defamatory, harassing, or infringes third-party intellectual property.</li>
              <li>Make false health, safety, or efficacy claims about any product.</li>
              <li>Circumvent platform disclosure rules (FTC, ASA, etc.) for sponsored content.</li>
              <li>Attempt to reverse-engineer, scrape, or probe the Service for vulnerabilities.</li>
              <li>Resell or sublicense access to the Service without written permission.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. AI-Generated Content</h2>
            <p>Scripts and videos are generated by AI and may be inaccurate, incomplete, or unsuitable. You are responsible for reviewing all AI output before publishing. You must add any legally required disclosures (e.g., #ad, &ldquo;Paid Partnership&rdquo;) to comply with applicable advertising law and platform policies.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Intellectual Property</h2>
            <p>You retain ownership of any original content you input. AI-generated outputs are provided to you under the terms of the underlying model provider (Google). We make no warranty of copyright ownership of AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Disclaimer of Warranties</h2>
            <p className="uppercase text-xs tracking-wide">The service is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied, including merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the service will be uninterrupted, error-free, or that AI outputs will be accurate.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Limitation of Liability</h2>
            <p className="uppercase text-xs tracking-wide">To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including lost profits or data, arising out of your use of the service, even if advised of the possibility of such damages. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Termination</h2>
            <p>We may suspend or terminate your access at any time for violation of these Terms or for any other reason with reasonable notice. You may delete your account at any time by emailing {CONTACT_EMAIL}.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Governing Law</h2>
            <p>These Terms are governed by applicable law. Disputes shall be resolved by binding arbitration or in the courts of the applicable jurisdiction, as permitted by law.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">11. Changes</h2>
            <p>We may update these Terms. Continued use after changes constitutes acceptance. Material changes will be notified via email.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">12. Contact</h2>
            <p>Questions? Email <a href={`mailto:${CONTACT_EMAIL}`} className="text-violet-400 underline">{CONTACT_EMAIL}</a>.</p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-[#2a2a2a] flex gap-6 text-sm text-[#a3a3a3]">
          <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
          <Link href="/dashboard" className="hover:text-white transition-colors">Back to App</Link>
        </div>
      </main>
    </div>
  )
}
